#!/bin/sh

set -e

action="$1"

if [ "$action" = configure ]; then
    # register the alternatives of x-window-manager manually
    # because dh_installwm doesn't register manpage as slave yet.
    update-alternatives --install /usr/bin/x-window-manager \
        x-window-manager /usr/bin/muffin 60 \
        --slave /usr/share/man/man1/x-window-manager.1.gz \
        x-window-manager.1.gz /usr/share/man/man1/muffin.1.gz
fi

#DEBHELPER#
